swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  # Route pour récupérer toutes les transactions d'un mois spécifique
  /accounts/{accountId}/transactions/by-month/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all transactions for a specific account and month
      description: API for retrieving all transactions of a specific account for the given month.
      parameters:
        - in: path
          name: accountId
          required: true
          description: Unique ID of the account
          type: string
        - in: path
          name: month
          required: true
          description: Month for which to retrieve transactions
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionList'
        '404':
          description: Account not found
        '500':
          description: Internal Server Error

  # Route pour récupérer et mettre à jour les détails d'une transaction spécifique
  /accounts/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get details of a specific transaction
      description: API for retrieving details of a specific transaction.
      parameters:
        - in: path
          name: accountId
          required: true
          description: Unique ID of the account
          type: string
        - in: path
          name: transactionId
          required: true
          description: Unique ID of the transaction
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

  # Route pour mettre à jour et supprimer les informations d'une transaction spécifique
  /accounts/{accountId}/transactions/{transactionId}/details:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction details
      description: API for updating the "details" field of a specific transaction.
      parameters:
        - in: path
          name: accountId
          required: true
          description: Unique ID of the account
          type: string
        - in: path
          name: transactionId
          required: true
          description: Unique ID of the transaction
          type: string
        - in: body
          name: body
          description: Updated transaction details
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction "details" updated successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete transaction details
      description: API for deleting the "details" field of a specific transaction.
      parameters:
        - in: path
          name: accountId
          required: true
          description: Unique ID of the account
          type: string
        - in: path
          name: transactionId
          required: true
          description: Unique ID of the transaction
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction "details" deleted successfully
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  Transaction:
    type: object
    properties:
      id:
        type: string
      accountId:
        type: string
      amount:
        type: number
      date:
        type: string
        format: date-time
      description:
        type: string

  TransactionList:
    type: array
    items:
      $ref: '#/definitions/Transaction'
